---
name: 🐛 Bug Report
description: Report an issue that should be fixed
labels:
  - bug
  - needs triage
body:
  - id: intro
    type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Make sure you are running the latest version.
        The bug you are experiencing may already have been fixed.

        Please try to include as much information as possible.
  - id: what-runtime-version
    type: input
    attributes:
      label: What version of runtime?
      description: |
        Copy the output of:
        - node: `node --version`
        - bun: `bun --version`
      placeholder: bun 0.0.0 / node v0.0.0
  - id: what-package-version
    type: input
    attributes:
      label: What version of `@kimzuni/templify` are you using?
      description: |
        Copy the output of:
        - node: `npm ls @kimzuni/templify`
        - bun: `bun pm ls | grep "@kimzuni/templify"`
      placeholder: 0.0.0
  - id: what-steps
    type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true
  - id: what-expected
    type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible, please provide text instead of a screenshot.
  - id: what-instead
    type: textarea
    attributes:
      label: What do you see instead?
      description: If possible, please provide text instead of a screenshot.
  - id: additional-information
    type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
