blank_issues_enabled: true
contact_links:
  - name: 💬 Ask a Question (Q&A)
    url: https://github.com/kimzuni-labs/templify/discussions/categories/q-a
    about: |
      Have a question or need help?
      Please open a thread in the Q&A section instead of creating an issue.
