---
name: CI

on:
  workflow_dispatch:
  push: &trigger
    branches:
      - main
    paths-ignore:
      - LICENSE
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".release-please/**"
  pull_request: *trigger

jobs:
  ci:
    if: >
      github.event_name != 'pull_request'
      || github.event.pull_request.draft == false
    permissions:
      id-token: write
      contents: read
    uses: kimzuni-labs/workflows/.github/workflows/bun-ci.yml@main
    with:
      build: true
      build-script: build:packages
      test: true
      codecov-upload: true
      lint: true
